dia=int(input("Digite numero de dia"))
match dia:
    case 1:print("lunes")
    case 2:print("Martes")
    case 3:print("Miercoles")
    case 4:print("Jueves")
    case 5:print("Viernes")
    case 6:print("Sabado")
    case 7:print("Domingo")
    case _:print("Opcion no valida")
